/* *******************
 * AUTO-GENERATED FILE
 * *******************
 * @NOTE This file is automatically generated from the contents of `@polyzone/core`
 * To regenerate this file, run `npm run build:core.g`
 *
 * DO NOT EDIT THIS FILE MANUALLY, AS ANY CHANGES TO IT WILL BE OVERWRITTEN.
 */

import * as Context from '@polyzone/core/Context';
import * as IEngine from '@polyzone/core/IEngine';
import * as Core from '@polyzone/core';
import * as UtilTypes from '@polyzone/core/util/types';
import * as TransformRotation from '@polyzone/core/transform/Rotation';
import * as Transform from '@polyzone/core/transform';
import * as TestMockEngine from '@polyzone/core/test/MockEngine';
import * as Test from '@polyzone/core/test';
import * as TestVitestPlugin from '@polyzone/core/test/vitest/plugin';
import * as TestVitestSetup from '@polyzone/core/test/vitest/setup';
import * as SceneScene from '@polyzone/core/scene/Scene';
import * as SceneSceneQuery from '@polyzone/core/scene/SceneQuery';
import * as Scene from '@polyzone/core/scene';
import * as ObjectsCustomScript from '@polyzone/core/objects/CustomScript';
import * as ObjectsGameObject from '@polyzone/core/objects/GameObject';
import * as ObjectsGameObjectComponent from '@polyzone/core/objects/GameObjectComponent';
import * as Objects from '@polyzone/core/objects';
import * as ObjectsComponentsCameraComponent from '@polyzone/core/objects/components/CameraComponent';
import * as ObjectsComponentsDirectionalLightComponent from '@polyzone/core/objects/components/DirectionalLightComponent';
import * as ObjectsComponentsMeshComponent from '@polyzone/core/objects/components/MeshComponent';
import * as ObjectsComponentsPointLightComponent from '@polyzone/core/objects/components/PointLightComponent';
import * as ObjectsComponentsScriptComponent from '@polyzone/core/objects/components/ScriptComponent';
import * as ObjectsComponents from '@polyzone/core/objects/components';
import * as MathColor3 from '@polyzone/core/math/Color3';
import * as MathColor4 from '@polyzone/core/math/Color4';
import * as MathVector2 from '@polyzone/core/math/Vector2';
import * as MathVector3 from '@polyzone/core/math/Vector3';
import * as Math from '@polyzone/core/math';
import * as MathUtil from '@polyzone/core/math/util';
import * as InputInput from '@polyzone/core/input/Input';
import * as Input from '@polyzone/core/input';

export interface CoreModuleDefinition {
  name: string;
  module: any;
}

// @NOTE These are all the imports that will be injected into scripts
// defined at runtime
export const CoreModules: CoreModuleDefinition[] = [
  {
    name: '@polyzone/core/Context',
    module: Context,
  },
  {
    name: '@polyzone/core/IEngine',
    module: IEngine,
  },
  {
    name: '@polyzone/core',
    module: Core,
  },
  {
    name: '@polyzone/core/util/types',
    module: UtilTypes,
  },
  {
    name: '@polyzone/core/transform/Rotation',
    module: TransformRotation,
  },
  {
    name: '@polyzone/core/transform',
    module: Transform,
  },
  {
    name: '@polyzone/core/test/MockEngine',
    module: TestMockEngine,
  },
  {
    name: '@polyzone/core/test',
    module: Test,
  },
  {
    name: '@polyzone/core/test/vitest/plugin',
    module: TestVitestPlugin,
  },
  {
    name: '@polyzone/core/test/vitest/setup',
    module: TestVitestSetup,
  },
  {
    name: '@polyzone/core/scene/Scene',
    module: SceneScene,
  },
  {
    name: '@polyzone/core/scene/SceneQuery',
    module: SceneSceneQuery,
  },
  {
    name: '@polyzone/core/scene',
    module: Scene,
  },
  {
    name: '@polyzone/core/objects/CustomScript',
    module: ObjectsCustomScript,
  },
  {
    name: '@polyzone/core/objects/GameObject',
    module: ObjectsGameObject,
  },
  {
    name: '@polyzone/core/objects/GameObjectComponent',
    module: ObjectsGameObjectComponent,
  },
  {
    name: '@polyzone/core/objects',
    module: Objects,
  },
  {
    name: '@polyzone/core/objects/components/CameraComponent',
    module: ObjectsComponentsCameraComponent,
  },
  {
    name: '@polyzone/core/objects/components/DirectionalLightComponent',
    module: ObjectsComponentsDirectionalLightComponent,
  },
  {
    name: '@polyzone/core/objects/components/MeshComponent',
    module: ObjectsComponentsMeshComponent,
  },
  {
    name: '@polyzone/core/objects/components/PointLightComponent',
    module: ObjectsComponentsPointLightComponent,
  },
  {
    name: '@polyzone/core/objects/components/ScriptComponent',
    module: ObjectsComponentsScriptComponent,
  },
  {
    name: '@polyzone/core/objects/components',
    module: ObjectsComponents,
  },
  {
    name: '@polyzone/core/math/Color3',
    module: MathColor3,
  },
  {
    name: '@polyzone/core/math/Color4',
    module: MathColor4,
  },
  {
    name: '@polyzone/core/math/Vector2',
    module: MathVector2,
  },
  {
    name: '@polyzone/core/math/Vector3',
    module: MathVector3,
  },
  {
    name: '@polyzone/core/math',
    module: Math,
  },
  {
    name: '@polyzone/core/math/util',
    module: MathUtil,
  },
  {
    name: '@polyzone/core/input/Input',
    module: InputInput,
  },
  {
    name: '@polyzone/core/input',
    module: Input,
  },
];
